version: "3.9"

services:
  web:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: .env.dev
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "web"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    expose:
      - 5432
    networks:
      - default

volumes:
  postgres_data: