# Generated by Django 4.2 on 2023-05-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=200)),
                ("balance_left", models.IntegerField(default=0)),
                ("sell_price", models.IntegerField(default=0)),
                ("target_address", models.CharField(max_length=200)),
                ("client_address", models.CharField(max_length=200)),
            ],
        ),
    ]
