# Generated by Django 4.2 on 2023-05-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datacollector", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerinfo",
            name="client_address",
        ),
        migrations.RemoveField(
            model_name="customerinfo",
            name="sell_price",
        ),
        migrations.AddField(
            model_name="customerinfo",
            name="client_email",
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customerinfo",
            name="selling_price",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="customerinfo",
            name="balance_left",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="customerinfo",
            name="store_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customerinfo",
            name="target_address",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
