# Generated by Django 4.2 on 2023-05-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datacollector", "0002_remove_customerinfo_client_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerinfo",
            name="target_network",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
